version: 2.1
jobs:
  buildfront:
    docker:
      - image: circleci/node:latest
    working_directory: ~/workspace
    steps:
      - checkout
      - run:
          name: Make build directory
          command: mkdir -p build/agd/EnterLeaveSystem && mkdir -p build/gl/EnterLeaveSystem
      - restore_cache:
          keys:
            - npm-{{ checksum "front/package-lock.json" }}
            - npm-
      - run:
          name: Install Dependency
          command: cd front && npm install
      - save_cache:
          key: npm-{{ checksum "front/package-lock.json" }}
          paths:
            - ~/workspace/front/node_modules
          force: yes
      - run:
          name: Build front for AizuGeekDojo version
          command: cd front && cp .env.agd .env.production && npm run build && mv dist ../build/agd/EnterLeaveSystem/
      - run:
          name: Build front for GlobalLounge version
          command: cd front && cp .env.gl .env.production && npm run build && mv dist ../build/gl/EnterLeaveSystem/
      - persist_to_workspace:
          root: ~/
          paths:
            - workspace

  buildserver:
    docker:
      - image: aizugeekdojo/cgo-arm:latest
    working_directory: /root/workspace/server
    steps:
      - attach_workspace:
          at: /root
      - run:
          name: Build server
          command: GO111MODULE=on go build -o ../build/elsystem main.go
      - run:
          name: Copy binary
          command: cp ../build/elsystem ../build/agd/EnterLeaveSystem/ && cp ../build/elsystem ../build/gl/EnterLeaveSystem/
      - persist_to_workspace:
          root: /root
          paths:
            - workspace

  release:
    docker:
      - image: aizugeekdojo/cgo-arm:latest
    working_directory: /root/workspace
    steps:
      - attach_workspace:
          at: /root
      - run:
          name: Copy other install files
          command: cp bin/* build/agd/EnterLeaveSystem/ && cp bin/* build/gl/EnterLeaveSystem/
      - run:
          name: Archive binary
          command: tar cvfz agd.tar.gz build/agd/EnterLeaveSystem/ && tar cvfz gl.tar.gz build/gl/EnterLeaveSystem/
      - store_artifacts:
          path: agd.tar.gz
          destination: agd.tar.gz
      - store_artifacts:
          path: gl.tar.gz
          destination: gl.tar.gz
workflows:
  version: 2
  build_release:
    jobs:
      - buildfront:
          filters:
            branches:
              only: add_cd
      - buildserver:
          requires:
            - buildfront
          filters:
            branches:
              only: add_cd
      - release:
          requires:
            - buildserver
          filters:
            branches:
              only: add_cd