@startuml sequence
actor User
participant Front
participant Server
database DB
participant CardReader

== Initialization ==
Server -> CardReader : Standby card reader
activate CardReader

Front -> User : Show top page
Front -> Server : Watch card reader
activate Server


== Detecting enter/leave ==
alt Detect student ID card or registered card
  User -> CardReader : Hold ID card
  CardReader -> Server : Return card info
  deactivate CardReader

  alt Card is not student ID card
    Server -> DB : Get user id
    activate DB
    DB -> Server : Return user id
    deactivate DB
  end

  Server -> Front : Return user info
  deactivate Server
  Server -> CardReader : Standby card reader
  activate CardReader
else Detect not registered card
  User -> CardReader : Hold ID card
  activate Server
  CardReader -> Server : Return card info
  deactivate CardReader
  Server -> DB : Get user id
  activate DB
  DB -> Server : Return not found
  deactivate DB

  Server -> Front : Return card info with "IsNew" is true
  deactivate Server

  Server -> CardReader : Standby card reader
  activate CardReader

  Front -> User : Show register page
  User -> Front : Register user ID

  Front -> Server : Register user ID with card info
  activate Server
  Server -> DB : Check user ID is valid
  activate DB
  DB -> Server : Return user ID is valid
  deactivate DB
  alt if user ID is not valid
  Server -> Front : Return ID is not valid
  Front -> User : Show alert
  end
  Server -> Front : Return OK
  deactivate Server
else Click forgot link
  User -> Front : Click forgot link
  activate Server
  Front -> Server : Stop watching card reader
  deactivate Server
  Front -> User : Show forgot page
  User -> Front : Send user ID

  Front -> Server : Request user info
  activate Server
  Server -> DB : Check user info
  activate DB
  DB -> Server : Return user info
  deactivate DB
  alt if user ID is not valid
  Server -> Front : Return ID is not valid
  Front -> User : Show alert
  end
  Server -> Front : Return user info
  deactivate Server
end

== Entering ==
... After detecting card or forgot ...
Front -> User : Show welcome page
Front -> Server : Send enter log
activate Server
Server -> DB : Insert enter log
activate DB
DB -> Server : Return OK
deactivate DB
Server -> Front : Return OK
deactivate Server
...A few seconds latter...
Front -> User : Show top page
Front -> Server : Watch card reader
activate Server

== Leaving ==
deactivate Server
... After detecting card or forgot ...
Front -> User : Show question page
alt if require question
  User -> Front : Answer qustion and click send button
end
Front -> Server : Send enter log
activate Server
Server -> DB : Insert enter log
activate DB
DB -> Server : Return OK
deactivate DB
Server -> Front : Return OK
deactivate Server
Front -> User : Show goodbye page
...A few seconds latter...
Front -> User : Show top page
Front -> Server : Watch card reader
activate Server

@enduml